package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("https://etherscan.io/dapp/0x7Fc545622fC3F14732838d8bdB27fF424af0d19A")
    void generatedTest() {
        step("Открыть https://etherscan.io/dapp/0x7Fc545622fC3F14732838d8bdB27fF424af0d19A", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://etherscan.io/dapp/0x7Fc545622fC3F14732838d8bdB27fF424af0d19A'", () ->
            open("https://etherscan.io/dapp/0x7Fc545622fC3F14732838d8bdB27fF424af0d19A"));

        step("Page title should have text 'Dapp Solomonic NFT SArt .beta (SArt.beta)'", () -> {
            String expectedTitle = "Dapp Solomonic NFT SArt .beta (SArt.beta)";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://etherscan.io/dapp/0x7Fc545622fC3F14732838d8bdB27fF424af0d19A'", () ->
            open("https://etherscan.io/dapp/0x7Fc545622fC3F14732838d8bdB27fF424af0d19A"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}